### ISSUE TITLE
Can't run on simulator

### ISSUE THREAD

**Issue by creatd** [Ink/ThatPDF#8]
I tried both master and develop branches, when I run on simulator, it crashed during launch

[NSFileManager copyItemAtPath:toPath:error:]: source path is nil
triggered from [Ink setupWithKey:@"..."]

Maybe I should be running on a device instead? (I don't have an iPad handy at the moment so couldn't test it)

**Comment by liyanchang** [comment]
Hi there,

Just pushed an update that should have all the right files. Sorry about that.

**Comment by creatd** [comment]
Yep I can confirm it works now, thanks
